name: 'Hello World'
description: 'Greet someone and record the time'
inputs:
  hugo-version:
    description:
      'The Hugo version to download.ts (if necessary) and use. Example: 0.58.2'
    required: false
    default: 'latest'
  extended:
    description:
      'Download (if necessary) and use Hugo extended version. Example: true'
    required: false
    default: 'false'
  dart-sass:
    description: 'Download (if necessary) dart-sass'
    required: false
    default: 'false'
  dart-sass-version:
    description:
      'The dart-sass version to download.ts (if necessary) and use. Example:
      1.76.0'
    required: false
    default: ''
  github-token:
    description:
      'Used to avoid rate limits when interacting with the Github API'
    required: false
    default: ''
runs:
  using: 'node20'
  main: 'dist/index.js'
